---
title: "Canopy Closure - Plotting"
author: "Nikola Arsenijevic"
date: "10/4/2019"
output: html_document
---


```{r include=FALSE}
library(tidyverse)
library(drc)
library(ggplot2)
library(lubridate)
library(tidyverse)
library(hrbrthemes)
library(plotly)
library(patchwork)
library(babynames)
library(viridis)
library(lme4)
library(nlme)
library(lmerTest)
library(emmeans)
library(car)
library(agricolae)
library(multcomp)
library(multcompView)
library(lattice)
library(ggpubr)
library(grid)
library(dplyr)
library(ggthemes)
```






```{r new data loading}
ed10 <- read_csv("ed1001.csv")
ed50 <- read_csv("ed50.csv")
ed90 <- read_csv("ed90.csv")
```





```{r ggplot ed10}

f10 <- ggplot(ed10, aes(x = trt, y=Estimate, label="."), inherit.aes=TRUE) + 
  geom_point (size = 4, shape = 15, aes(colour = Estimate)) + 
  geom_errorbar(aes(ymin  =  lower.CL, ymax  =  upper.CL), width =  0.2, size  =  0.7) +
  ylim(150, 208) + scale_x_continuous(limits = c(0,16), breaks = c(1, 2, 3 ,4, 5, 6, 7, 8, 9, 10, 11, 12 ,13 ,14 ,15 ,16)) + theme_classic() + xlab(".") +
  ylab("DAY OF THE YEAR") + theme(axis.title = element_text(face = "bold"), 
                     axis.text = element_text(face = "bold"), 
                     plot.caption = element_text(hjust = 0))
  
f10
```



```{r ggplot ed50}
f50 <- ggplot(ed50, aes(x = trt, y=Estimate, label="."), inherit.aes=TRUE) + 
  geom_point (size = 4, shape = 15, aes(colour = Estimate)) + 
  geom_errorbar(aes(ymin  =  lower.CL, ymax  =  upper.CL), width =  0.2, size  =  0.7) + theme_classic() +
  theme(axis.title   = element_text(face = "bold"), 
                     axis.text = element_text(face = "bold"), 
                     plot.caption = element_text(hjust = 0)) + ylim(150, 208) + scale_x_continuous(name = "TREATMENT", limits = c(0,16), breaks = c(1, 2, 3 ,4, 5, 6, 7, 8, 9, 10, 11, 12 ,13 ,14 ,15 ,16)) + 
  xlab("TREATMENT") + theme(axis.title.y = element_blank())

f50
```



```{r ggplot ed90}
f90 <- ggplot(ed90, aes(x = trt, y=Estimate, label="."), inherit.aes=TRUE) + 
  geom_point (size = 4, shape = 15, aes(colour = Estimate)) + 
  geom_errorbar(aes(ymin  =  lower.CL, ymax  =  upper.CL), width =  0.2, size  =  0.7) +
  ylim(150, 208) + scale_x_continuous(limits = c(0,16), breaks = c(1, 2, 3 ,4, 5, 6, 7, 8, 9, 10, 11, 12 ,13 ,14 ,15 ,16)) + 
  theme_classic() + theme(axis.title.y = element_blank(),
                          axis.title = element_text(face = "bold"))+ theme(axis.title   = element_text(face = "bold"), 
                     axis.text = element_text(face = "bold"), 
                     plot.caption = element_text(hjust = 0)) + xlab(".")

f90
```



```{r}
finalfigure <- ggarrange(f10, f50, f90, labels = c("ED10", "ED50", "ED90"),
                         legend = "bottom", label.x = 0.1, label.y = 1.00005, ncol = 3, nrow = 1,
                         hjust = -0.35, vjust = 2,
                         font.label = list(size = 30, face = "bold", color="red"))

finalfigure
```